import { useMemo } from "react";
import { Pressable, ScrollView, Text, TextInput, View, useWindowDimensions } from "react-native";
import { Image } from "expo-image";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import type { Layout_dash_labScreenData, Layout_dash_labScreenEvents } from "@/contracts/layout-dash-lab";
import { containerStyle, nodeStyle } from "@/runtime/layout";
import { createIntentFormStyles } from "@/theme/styles";
import { useIntentFormTheme } from "@/theme/tokens";



export interface Layout_dash_labScreenProps {
  data: Layout_dash_labScreenData;
  events: Layout_dash_labScreenEvents;
}

export function Layout_dash_labScreen({ data, events }: Layout_dash_labScreenProps) {
  const { width, height } = useWindowDimensions();
  const insets = useSafeAreaInsets();
  const compact = width <= 390 || height <= 700;
  const theme = useIntentFormTheme();
  const styles = useMemo(() => createIntentFormStyles(theme), [theme]);
  const persistent = false;
  return (
    <View style={styles.screen} testID="screen-layout-lab">
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={[styles.scrollContent, { paddingBottom: persistent ? 24 : Math.max(insets.bottom, 24) }]}
      >
        <View style={styles.header}>
          <Text selectable style={styles.eyebrow}>{"Verdant Pay"}</Text>
          <Text selectable accessibilityRole="header" style={styles.title}>{"Layout lab"}</Text>
          <Text selectable style={styles.body}>{"Exercise every recursive layout relation"}</Text>
        </View>
        <View style={styles.content}>
          <View testID="node-layout-lab.adaptive" style={nodeStyle({"compactMode":"stack","regularMode":"grid","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.adaptive" style={containerStyle({"compactMode":"stack","regularMode":"grid","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.safe-area" style={nodeStyle({"compactMode":"safe-area","regularMode":"safe-area","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.safe-area" style={containerStyle({"compactMode":"safe-area","regularMode":"safe-area","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.grid" style={nodeStyle({"compactMode":"grid","regularMode":"grid","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.grid" style={containerStyle({"compactMode":"grid","regularMode":"grid","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.grid-a" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Grid A" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Grid A"}</Text></View></View>
<View testID="node-layout-lab.grid-b" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Grid B" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Grid B"}</Text></View></View></View></View></View></View>
<View testID="node-layout-lab.overlay" style={nodeStyle({"compactMode":"overlay","regularMode":"overlay","axis":"overlay","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.overlay" style={containerStyle({"compactMode":"overlay","regularMode":"overlay","axis":"overlay","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.overlay-a" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Overlay base" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Overlay base"}</Text></View></View>
<View testID="node-layout-lab.overlay-b" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Overlay foreground" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Overlay foreground"}</Text></View></View></View></View>
<View testID="node-layout-lab.scroll" style={nodeStyle({"compactMode":"scroll","regularMode":"scroll","axis":"horizontal","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"scroll","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.scroll" style={containerStyle({"compactMode":"scroll","regularMode":"scroll","axis":"horizontal","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"scroll","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.wrap" style={nodeStyle({"compactMode":"wrap","regularMode":"wrap","axis":"horizontal","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.wrap" style={containerStyle({"compactMode":"wrap","regularMode":"wrap","axis":"horizontal","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.wrap-a" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Wrap A" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Wrap A"}</Text></View></View>
<View testID="node-layout-lab.wrap-b" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Wrap B" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Wrap B"}</Text></View></View></View></View></View></View>
<View testID="node-layout-lab.split" style={nodeStyle({"compactMode":"split","regularMode":"split","axis":"horizontal","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.4,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.split" style={containerStyle({"compactMode":"split","regularMode":"split","axis":"horizontal","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.4,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.page-flow" style={nodeStyle({"compactMode":"page-flow","regularMode":"page-flow","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.page-flow" style={containerStyle({"compactMode":"page-flow","regularMode":"page-flow","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.page" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Page flow" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Page flow"}</Text></View></View></View></View>
<View testID="node-layout-lab.stack" style={nodeStyle({"compactMode":"stack","regularMode":"stack","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.stack" style={containerStyle({"compactMode":"stack","regularMode":"stack","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.stack-item" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"gap":16,"padding":20})}><View accessible accessibilityLabel="Stack" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"Stack"}</Text></View></View></View></View></View></View>
<View testID="node-layout-lab.freeform" style={nodeStyle({"compactMode":"freeform","regularMode":"freeform","axis":"vertical","width":"fill","height":"fixed","fixedHeight":180,"align":"stretch","justify":"start","overflow":"clip","columns":2,"splitRatio":0.5,"gap":12,"padding":16})}><View accessible accessibilityLabel="layout-lab.freeform" style={containerStyle({"compactMode":"freeform","regularMode":"freeform","axis":"vertical","width":"fill","height":"fixed","fixedHeight":180,"align":"stretch","justify":"start","overflow":"clip","columns":2,"splitRatio":0.5,"gap":12,"padding":16}, compact)}><View testID="node-layout-lab.freeform-a" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"position":{"x":12,"y":18,"z":2},"gap":16,"padding":20})}><View accessible accessibilityLabel="layout-lab.freeform-a" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"layout-lab.freeform-a"}</Text></View></View>
<View testID="node-layout-lab.freeform-b" style={nodeStyle({"compactMode":"leaf","regularMode":"leaf","axis":"vertical","width":"fill","height":"hug","align":"stretch","justify":"start","overflow":"visible","columns":2,"splitRatio":0.5,"position":{"x":84,"y":44,"z":1},"gap":16,"padding":20})}><View accessible accessibilityLabel="layout-lab.freeform-b" accessibilityLiveRegion="polite" style={styles.status}><Text selectable style={styles.body}>{"layout-lab.freeform-b"}</Text></View></View></View></View></View></View>
        </View>
      </ScrollView>

    </View>
  );
}
